version: '3'
services:
  postgres:
    build:
      context: .
      dockerfile: ./postgres.dockerfile
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./:/work
      - ./db_data:/var/lib/postgresql/data
    working_dir: /work
  
  client:
    image: node:20-alpine
    ports:
      - 3000:3000
    volumes:
      - ./client:/client
    working_dir: /client
    entrypoint: npm run dev
  
  redis:
    image: redis:7-alpine
    ports:
      - 6379:6379
  
  server:
    build:
      context: .
      dockerfile: ./server/server.dockerfile
    ports:
      - 9090:9090
    volumes:
      - ./server:/server
    working_dir: /server
    entrypoint: npm run dev