version: '3'
services:
  db:
    build: .
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./:/work
    working_dir: /work
  
  client:
    image: node:20-alpine
    ports:
      - 3000:3000
    volumes:
      - ./client:/client
    working_dir: /client
    entrypoint: npm run dev